image: node:10.13.0

cache:
  paths:
    - node_modules/

stages:
  - test

Test:
  stage: test
  tags:
    - node
  before_script:
    - npm install
  script:
    - npm run test --coverage --no-color
  coverage: /All files\s*\|\s*([\d\.]+)/
